{% set version = "42.0.5" %}

package:
  name: cryptography-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/cryptography/cryptography-{{ version }}.tar.gz
    sha256: 6fe07eec95dfd477eb9530aef5bead34fec819b3aaf6c5bd6d20565da607bfe1
    folder: cryptography
  - url: https://pypi.io/packages/source/c/cryptography_vectors/cryptography_vectors-{{ version }}.tar.gz
    sha256: 505cd5e3b0cb32da1526f07042b7fc38a4b6c356710cb73d2b5f76b037a38ed1
    folder: cryptography-vectors

build:
  number: 0
  skip: true  # [py<38]

outputs:
  - name: cryptography-vectors
    # releases of cryptrography and cryptography-vectors are released in sync
    script: bldsplit.sh # [unix]
    script: bldsplit.bat # [win]
    requirements:
      host:
        - python
        - pip
        - flit-core
      run:
        - python
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - cryptography_vectors
    about:
      home: https://github.com/pyca/cryptography
      license: Apache-2.0 OR BSD-3-Clause
      license_family: OTHER
      license_file:
        - cryptography-vectors/LICENSE
        - cryptography-vectors/LICENSE.APACHE
        - cryptography-vectors/LICENSE.BSD
      summary: Test vectors for cryptography.
      description: |
        This package contains test vectors for the cryptography package.
      dev_url: https://github.com/pyca/cryptography/tree/main/vectors
      doc_url: https://cryptography.io/

  - name: cryptography
    script: bldsplit.sh # [unix]
    script: bldsplit.bat # [win]
    build:
      missing_dso_whitelist:  # [s390x]
        - $RPATH/ld64.so.1    # [s390x]
    requirements:
      build:
        - {{ compiler('rust') }}
        - vs2017_{{ target_platform }}    # [win]
      host:
        - python
        - pip
        - setuptools >=61.0.0
        - setuptools-rust >=1.7.0
        - wheel
        - openssl {{openssl}}
        - cffi 1.15.1
      run:
        - python
        - cffi >=1.12
        - openssl
        - libgcc-ng     # [linux]; needed by `_rust.abi3.so`
    test:
      requires:
        - certifi
        - cryptography-vectors {{ version }}
        - pip
        - pytest >=6.2.0
        - pytest-benchmark
        - pytest-cov
        - pytest-xdist
        - pretend
      source_files:
        - cryptography/tests
        - cryptography/pyproject.toml
      commands:
        - pip check
        # run_test.py will check that the correct openssl version is linked
        - pytest -n auto
    about:
      home: https://github.com/pyca/cryptography
      license: Apache-2.0 OR BSD-3-Clause
      license_family: OTHER
      license_file:
        - cryptography/LICENSE
        - cryptography/LICENSE.APACHE
        - cryptography/LICENSE.BSD
      summary: Provides cryptographic recipes and primitives to Python developers
      description: |
        cryptography is a package which provides cryptographic recipes and
        primitives to Python developers. Our goal is for it to be your
        "cryptographic standard library".
        cryptography includes both high level recipes and low level interfaces to
        common cryptographic algorithms such as symmetric ciphers, message digests,
        and key derivation functions.
      dev_url: https://github.com/pyca/cryptography
      doc_url: https://cryptography.io/

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - chenghlee
