travis:
  secure:
    BINSTAR_TOKEN: S8AvUyaHjUj9FKPZbMDDl6aown+AFr8vEHRfa820r+izYZ8npvl6Nd5Hbc0VMRdlg45GGPIF7/h/q280j9BONIZPhKCQmSMk25HTHwbxthdulmiJh1fIgJZfMK2e3KNE96KRIUk8B5zGOsPQUMDB/eLTriEnTqn9uxqmxh4XGim6Z1E3s1KQqI4SUwLlFQuCE7+RyM9h/nQGX3hsYs02DLUSqW02KYznBC7szo+9txvZQnu5DslCHGJ4FYEHH3DEYvtmRQ6wa4yvU93PxpbFhsYmDkn7B9RCvusTxoiF1rZafuRvqrc3VKNbWNgP0L/PzLipIbrvEvqESLOFNbbcPHYzS7a+QF1joTpFnLCltbcljUkHJoXwnk0IljoQkJoRixD6Z7jUphq4TuQYwYG9JPEsSriwuXuVbSEB68ZSEUkwHlUemvRT8nzAHNvoQX4++8slWK2ApjAXUFnsmyjzJZ6dwSHc5nlFPg/c20K5Tg3POXlzbut7R3hGjl1VA6C1YI0rElamLVlvpQ5pm8xVsPxpCmrS0/u8t5B/q5cHyXOHO2KRE9ys8q0cBeg4o2ehBAnwh8xPlYtsVk5OacK/9COjq3rT17PUgpaixLeC2EWQMmw3vL757iDDT7cn7R/XpSloHPGf1APhwafTcc+h0N2ZYKieLZ1qtIa7FUAcZHo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
